---
deployment:
  tasks:
    # 1. Definisikan path tujuan
    - export DEPLOYPATH=/home/shineedu/fe-shineeducationbali/
    
    # 2. Salin semua file dari repositori ke folder live
    - /bin/cp -r * $DEPLOYPATH
    
    # 3. Aktifkan Node.js virtual environment
    - source /home/shineedu/nodevenv/fe-shineeducationbali/22/bin/activate